### ISSUE TITLE
doc bug:  auger.json

### ISSUE THREAD

**Issue by rayleeriver** [augerai/a2ml#119]
Per README.md, I tried to run a2ml with downloaded auger.json file.  However, because auger.json contains "organization_id", I got the following error:

> [auger]  No name or id was specified for Organization

I had to change "organization_id" to "organization" with the name of the organization for a2ml to work.

**Comment by knobotz** [comment]
@rayleeriver a fix for this was pushed to the Auger.AI provider, so it should be working now. Please give it a try.

**Comment by rayleeriver** [comment]
I tried these steps just now:
` pip3 install -U a2ml`
`a2ml dataset list`  (config.yaml has providers: auger, auger.json has "organization_id": 1100)

I'm still getting:
` [auger]  No name or id was specified for Organization`

**Comment by knobotz** [comment]
@rayleeriver there might have been a cache of the javascript assets that produce this downloaded file. Could you try refreshing your browser and downloading the file again? From my side it downloads an `auger.json` file with the following structure:
